/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 raw_assets\Scene_1_Winter.glb -T -j -M 
Files: raw_assets\Scene_1_Winter.glb [2.79MB] > C:\Users\andre\My Stuff\VS Code Projects\tutorials\aimees-papercraft-portfolio\Scene_1_Winter-transformed.glb [225.48KB] (92%)
*/

import { useKTX2Texture } from "../utils/ktxLoader";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { AnimateMesh } from "../components/AnimateMesh";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/Scene_1_Winter-transformed.glb",
  );

  const texture_1 = useKTX2Texture("/textures/Scene_1_Winter_1.webp", false);
  const texture_2 = useKTX2Texture("/textures/Scene_1_Winter_2.webp", false);
  const texture_3 = useKTX2Texture("/textures/Scene_1_Winter_3.webp", false);
  const texture_4 = useKTX2Texture("/textures/Scene_1_Winter_4.webp", false);

  const flame1Ref = useRef();
  const flame2Ref = useRef();
  const flame3Ref = useRef();

  useFrame((state, delta) => {
    const time = state.clock.elapsedTime;

    const snapIndex = Math.floor(state.clock.elapsedTime * 100);
    const randomAngle =
      (Math.sin(snapIndex * 127.1) * 43758.5453) % (Math.PI * 2);

    if (flame1Ref.current) flame1Ref.current.rotation.y = -randomAngle;
    if (flame3Ref.current) flame3Ref.current.rotation.y = -randomAngle;
    if (flame2Ref.current) flame2Ref.current.rotation.y = randomAngle;
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Scene_1_Winter_1_Baked.geometry}
        material={texture_1}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_2_Baked.geometry}
        material={texture_2}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Player.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Bird_Wing.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Bird_Tail.geometry}
        material={texture_3}
      />

      <AnimateMesh
        position={nodes.Scene_1_Winter_3_Deer_Head.position}
        axis={"z"}
        amplitude={0.2}
        speed={1.5}
      >
        <mesh
          geometry={nodes.Scene_1_Winter_3_Deer_Head.geometry}
          material={texture_3}
        />
      </AnimateMesh>

      <mesh
        ref={flame1Ref}
        geometry={nodes.Scene_1_Winter_3_Fire_Inner_Most.geometry}
        position={nodes.Scene_1_Winter_3_Fire_Inner_Most.position}
        rotation={nodes.Scene_1_Winter_3_Fire_Inner_Most.rotation}
        material={texture_3}
      />
      <mesh
        ref={flame2Ref}
        geometry={nodes.Scene_1_Winter_3_Fire_Center.geometry}
        position={nodes.Scene_1_Winter_3_Fire_Center.position}
        rotation={nodes.Scene_1_Winter_3_Fire_Center.rotation}
        material={texture_3}
      />
      <mesh
        ref={flame3Ref}
        geometry={nodes.Scene_1_Winter_3_Fire_Outer.geometry}
        position={nodes.Scene_1_Winter_3_Fire_Outer.position}
        rotation={nodes.Scene_1_Winter_3_Fire_Outer.rotation}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Bird_Baked.geometry}
        position={nodes.Scene_1_Winter_3_Bird_Baked.position}
        material={texture_3}
      />
      {/* <mesh
        geometry={nodes.Scene_1_Winter_3_Chat_Box_Scene_1_Winter_3.geometry}
        material={texture_3}
      /> */}
      <AnimateMesh axis={"z"} amplitude={0.01}>
        <mesh
          geometry={nodes.Scene_1_Winter_3_Note_1.geometry}
          material={texture_3}
        />
      </AnimateMesh>

      <AnimateMesh axis={"z"} amplitude={0.012} speed={0.95}>
        <mesh
          geometry={nodes.Scene_1_Winter_3_Note_2.geometry}
          material={texture_3}
        />
      </AnimateMesh>
      <AnimateMesh axis={"z"} offset={0.3} amplitude={0.011} speed={0.99}>
        <mesh
          geometry={nodes.Scene_1_Winter_3_Note_3.geometry}
          material={texture_3}
        />
      </AnimateMesh>
      {/* 
      <mesh
        geometry={nodes.Scene_1_Winter_3_Hello_Text.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Thanks_Baked.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Welcome_Baked.geometry}
        material={texture_3}
      /> */}
      <mesh
        geometry={nodes.Scene_1_Winter_3_Flame_1.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Flame_2.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Flame_3.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_4_Baked.geometry}
        material={texture_4}
      />
    </group>
  );
}

useGLTF.preload("/models/Scene_1_Winter-transformed.glb");
